import Game from '../Game.js';

class TicTacToe extends Game {
    constructor() {
        super({ title: 'Tic-Tac-Toe Cafe', containerId: 'ttt-board' });

        this.board = [];
        this.currentPlayer = 'X';
        this.gameActive = true;
        this.gameMode = 'ai';
        this.boardSize = 3;
        this.winLength = 3;
        this.gameVariation = 'classic';

        this.boardElement = null;
        this.statusText = null;
        this.gameModeSelect = null;
        this.boardSizeSelect = null;
        this.gameVariationSelect = null;
    }

    init() {
        this.initBaseUI();

        const gameHtml = `
            <div class="flex flex-col items-center gap-10 w-full max-w-2xl mx-auto px-4 py-8">
                <!-- Wooden Hanging Sign Turn Indicator -->
                <div class="wooden-sign">
                    <div id="ttt-status" class="text-3xl font-black font-header text-amber-50 uppercase tracking-wider drop-shadow-md"></div>
                </div>

                <!-- Framed Parchment Board -->
                <div class="ttt-board-container w-full aspect-square max-w-[500px]">
                    <div id="ttt-board" class="grid w-full h-full">
                        <!-- Cells generated by JS -->
                    </div>
                </div>

                <!-- Vintage Menu Controls -->
                <div id="ttt-controls" class="menu-panel w-full space-y-8">
                    <div class="grid grid-cols-2 gap-8">
                        <div class="space-y-3">
                            <label class="block text-xs font-black uppercase tracking-widest text-sienna opacity-70">Mode</label>
                            <select id="ttt-game-mode" class="w-full bg-white/50 border border-sienna/20 rounded-xl p-4 font-bold text-stone-700 outline-none focus:ring-4 focus:ring-amber-100 transition-all cursor-pointer">
                                <option value="ai">Vs Barista AI</option>
                                <option value="local">Local Multiplayer</option>
                            </select>
                        </div>
                        <div class="space-y-3">
                            <label class="block text-xs font-black uppercase tracking-widest text-sienna opacity-70">Board Size</label>
                            <select id="ttt-board-size" class="w-full bg-white/50 border border-sienna/20 rounded-xl p-4 font-bold text-stone-700 outline-none focus:ring-4 focus:ring-amber-100 transition-all cursor-pointer">
                                <option value="3">3x3 (Classic)</option>
                                <option value="4">4x4 (Connect 4)</option>
                                <option value="5">5x5 (Connect 4)</option>
                            </select>
                        </div>
                    </div>
                    <div class="space-y-3">
                        <label class="block text-xs font-black uppercase tracking-widest text-sienna opacity-70">Variation</label>
                        <select id="ttt-variation" class="w-full bg-white/50 border border-sienna/20 rounded-xl p-4 font-bold text-stone-700 outline-none focus:ring-4 focus:ring-amber-100 transition-all cursor-pointer">
                            <option value="classic">Classic (Get line to win)</option>
                            <option value="misere">Misère (Try not to win)</option>
                        </select>
                    </div>
                    <div class="pt-4">
                        <button id="ttt-restart-btn" class="w-full wood-btn leading-none text-xl uppercase tracking-[0.2em]">
                            New Game
                        </button>
                    </div>
                </div>
            </div>
        `;
        document.getElementById('game-mount').innerHTML = gameHtml;

        this.boardElement = document.getElementById('ttt-board');
        this.statusText = document.getElementById('ttt-status');
        this.gameModeSelect = document.getElementById('ttt-game-mode');
        this.boardSizeSelect = document.getElementById('ttt-board-size');
        this.gameVariationSelect = document.getElementById('ttt-variation');
        this.restartBtn = document.getElementById('ttt-restart-btn');

        this.setupEventListeners();
        this.start();
    }

    setupEventListeners() {
        this.restartBtn.addEventListener('click', () => this.restart());

        this.gameModeSelect.addEventListener('change', () => {
            this.gameMode = this.gameModeSelect.value;
            this.restart();
        });

        this.boardSizeSelect.addEventListener('change', () => {
            this.boardSize = parseInt(this.boardSizeSelect.value);
            this.winLength = this.boardSize === 3 ? 3 : 4;
            this.restart();
        });

        this.gameVariationSelect.addEventListener('change', () => {
            this.gameVariation = this.gameVariationSelect.value;
            this.restart();
        });
    }

    start() {
        this.board = Array(this.boardSize * this.boardSize).fill(null);
        this.currentPlayer = 'X';
        this.gameActive = true;
        this.isGameOver = false;

        this.renderBoard();
        this.updateStatus();
    }

    renderBoard() {
        this.boardElement.innerHTML = '';
        this.boardElement.style.gridTemplateColumns = `repeat(${this.boardSize}, 1fr)`;

        for (let i = 0; i < this.boardSize * this.boardSize; i++) {
            const cell = document.createElement('div');
            cell.className = 'ttt-cell cursor-pointer transition-all hover:bg-amber-50';
            cell.dataset.index = i;

            // Apply borders dynamically for grid look
            const row = Math.floor(i / this.boardSize);
            const col = i % this.boardSize;
            if (col < this.boardSize - 1) cell.style.borderRight = '2px solid rgba(111, 78, 55, 0.3)';
            if (row < this.boardSize - 1) cell.style.borderBottom = '2px solid rgba(111, 78, 55, 0.3)';

            cell.addEventListener('click', () => this.handleCellClick(i));
            this.boardElement.appendChild(cell);
        }
    }

    handleCellClick(index) {
        if (!this.gameActive || this.board[index] !== null) return;

        this.makeMove(index);
    }

    makeMove(index) {
        this.board[index] = this.currentPlayer;
        this.updateCellUI(index);

        const winnerInfo = this.checkWinner();
        if (winnerInfo) {
            this.endGame(winnerInfo);
        } else if (this.board.every(cell => cell !== null)) {
            this.endGame(null, true);
        } else {
            this.currentPlayer = this.currentPlayer === 'X' ? 'O' : 'X';
            this.updateStatus();

            if (this.gameMode === 'ai' && this.currentPlayer === 'O' && this.gameActive) {
                this.boardElement.classList.add('pointer-events-none');
                setTimeout(() => this.aiMove(), 600);
            }
        }
    }

    updateCellUI(index) {
        const cell = this.boardElement.children[index];
        const symbol = this.board[index];
        if (symbol === 'X') {
            cell.innerHTML = `
                <div class="symbol-container">
                    <svg class="w-full h-full x-symbol" fill="none" viewBox="0 0 24 24">
                        <path stroke="#A0522D" stroke-linecap="round" stroke-linejoin="round" stroke-width="2.5" d="M6 18L18 6M6 6l12 12"></path>
                    </svg>
                </div>`;
        } else if (symbol === 'O') {
            cell.innerHTML = `
                <div class="symbol-container">
                    <svg class="w-full h-full o-symbol" fill="none" viewBox="0 0 24 24">
                        <path stroke="#6F4E37" stroke-linecap="round" stroke-linejoin="round" stroke-width="2.5" d="M12 22C6.477 22 2 17.523 2 12S6.477 2 12 2s10 4.477 10 10-4.477 10-10 10z"></path>
                    </svg>
                </div>`;
        }
    }

    updateStatus() {
        if (!this.gameActive) return;
        this.statusText.textContent = `Player ${this.currentPlayer}'s Turn`;
    }

    checkWinner() {
        const lines = this.getWinningLines();
        for (const line of lines) {
            const firstSymbol = this.board[line[0]];
            if (firstSymbol && line.every(index => this.board[index] === firstSymbol)) {
                return { winner: firstSymbol, line };
            }
        }
        return null;
    }

    getWinningLines() {
        const lines = [];
        // Rows & Columns
        for (let i = 0; i < this.boardSize; i++) {
            for (let j = 0; j <= this.boardSize - this.winLength; j++) {
                lines.push(Array.from({ length: this.winLength }, (_, k) => i * this.boardSize + j + k));
                lines.push(Array.from({ length: this.winLength }, (_, k) => (j + k) * this.boardSize + i));
            }
        }
        // Diagonals
        for (let i = 0; i <= this.boardSize - this.winLength; i++) {
            for (let j = 0; j <= this.boardSize - this.winLength; j++) {
                lines.push(Array.from({ length: this.winLength }, (_, k) => (i + k) * this.boardSize + (j + k)));
                lines.push(Array.from({ length: this.winLength }, (_, k) => (i + k) * this.boardSize + (j + this.winLength - 1 - k)));
            }
        }
        return lines;
    }

    endGame(winnerInfo, isDraw = false) {
        this.gameActive = false;
        if (isDraw) {
            this.statusText.textContent = "It's a Draw!";
            this.showGameOver("It's a Draw!", "Perfectly balanced. Care for another?");
        } else {
            const symbol = winnerInfo.winner;
            let winner = symbol;
            if (this.gameVariation === 'misere') {
                winner = symbol === 'X' ? 'O' : 'X';
            }
            this.statusText.textContent = `Player ${winner} Wins!`;
            this.highlightWinningLine(winnerInfo.line);
            this.showGameOver(`Player ${winner} Wins!`, "A strategic victory, like a finely roasted bean.");
        }
    }

    highlightWinningLine(line) {
        line.forEach(index => {
            this.boardElement.children[index].classList.add('bg-amber-100');
        });
    }

    aiMove() {
        const bestMove = this.findBestMove(this.board, 'O');
        if (bestMove.index !== -1) {
            this.makeMove(bestMove.index);
        }
        this.boardElement.classList.remove('pointer-events-none');
    }

    findBestMove(currentBoard, player) {
        let bestVal = -Infinity;
        let bestMove = { index: -1 };
        const availableMoves = currentBoard.map((s, i) => s === null ? i : null).filter(i => i !== null);

        // Limit depth for larger boards to keep it snappy
        const maxDepth = this.boardSize === 3 ? 10 : 4;

        for (const i of availableMoves) {
            currentBoard[i] = player;
            let moveVal = this.minimax(currentBoard, 0, false, -Infinity, Infinity, maxDepth);
            currentBoard[i] = null;
            if (moveVal > bestVal) {
                bestMove.index = i;
                bestVal = moveVal;
            }
        }
        return bestMove;
    }

    minimax(currentBoard, depth, isMax, alpha, beta, maxDepth) {
        const winnerInfo = this.checkWinner();
        if (winnerInfo) {
            const multiplier = this.gameVariation === 'classic' ? 1 : -1;
            return (winnerInfo.winner === 'O' ? 10 - depth : -10 + depth) * multiplier;
        }
        if (depth >= maxDepth || currentBoard.every(cell => cell !== null)) return 0;

        if (isMax) {
            let best = -Infinity;
            for (let i = 0; i < currentBoard.length; i++) {
                if (currentBoard[i] === null) {
                    currentBoard[i] = 'O';
                    best = Math.max(best, this.minimax(currentBoard, depth + 1, false, alpha, beta, maxDepth));
                    currentBoard[i] = null;
                    alpha = Math.max(alpha, best);
                    if (beta <= alpha) break;
                }
            }
            return best;
        } else {
            let best = Infinity;
            for (let i = 0; i < currentBoard.length; i++) {
                if (currentBoard[i] === null) {
                    currentBoard[i] = 'X';
                    best = Math.min(best, this.minimax(currentBoard, depth + 1, true, alpha, beta, maxDepth));
                    currentBoard[i] = null;
                    beta = Math.min(beta, best);
                    if (beta <= alpha) break;
                }
            }
            return best;
        }
    }

    restart() {
        this.start();
    }
}

export default TicTacToe;
